steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --pull
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: asia-southeast1-docker.pkg.dev/example-project/harbor-crm/api:manual
options:
  logging: CLOUD_LOGGING_ONLY
